apiVersion: v1
kind: Service
metadata:
  name: webhook
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health?format=json
    alb.ingress.kubernetes.io/success-codes: '200'
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: webhook
