version: "3.4"

services:
  api:
    image: ${DVC_VIEWER_BACKEND_IMAGE}:${DVC_VIEWER_RELEASE_VERSION}
    restart: always
    environment:
      ALLOWED_HOSTS: "*"
      SOCIAL_AUTH_REDIRECT_IS_HTTPS: "False"

      <<: &base_settings
        CELERY_BROKER_URL: ${REDIS_URL:-redis://redis:6379}
        CELERY_RESULT_BACKEND: ${REDIS_URL:-redis://redis:6379}
        DATABASE_URL: ${POSTGRES_URL:-psql://postgres:pwd111@postgres:5432/dvc}
        SECRET_KEY: ${SECRET_KEY:-"sjwx00s&zu5yz&r(fh4i7pi6c4ukf!9a17rdgyfbfwfo#w%9%0"}
        UI_URL: ${UI_URL:-http://localhost:3000}

        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-}
        GITHUB_SECRET_KEY: ${GITHUB_SECRET_KEY:-}
        GITHUB_WEBHOOK_URL: ${GITHUB_WEBHOOK_URL:-}
        GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET:-}

        GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID:-}
        GITLAB_SECRET_KEY: ${GITLAB_SECRET_KEY:-}
        GITLAB_WEBHOOK_URL: ${GITLAB_WEBHOOK_URL:-}
        GITLAB_WEBHOOK_SECRET: ${GITLAB_WEBHOOK_SECRET:-}
        GITLAB_URL: ${GITLAB_URL:-}

        BITBUCKET_CLIENT_ID: ${BITBUCKET_CLIENT_ID:-}
        BITBUCKET_SECRET_KEY: ${BITBUCKET_SECRET_KEY:-}
        BITBUCKET_WEBHOOK_URL: ${BITBUCKET_WEBHOOK_URL:-}
    ports:
      - 8000:8000

  ui:
    image: ${DVC_VIEWER_UI_IMAGE}:${DVC_VIEWER_RELEASE_VERSION}
    restart: always
    environment:
      API_URL: ${API_URL:-http://localhost:8000/api}
      SCM_PROVIDERS: ${SCM_PROVIDERS:-github,gitlab,bitbucket}
      FLAGS: ${FLAGS:-}
    ports:
      - 3000:3000

  worker:
    command:
      - celery
      - worker
      - -Aviewer
      - -linfo
      - -Pthreads
      - -c4
    image: ${DVC_VIEWER_BACKEND_IMAGE}:${DVC_VIEWER_RELEASE_VERSION}
    restart: always
    deploy:
      replicas: 2
    environment:
      <<: *base_settings

  beat:
    command:
      - celery
      - beat
      - -Aviewer
      - -linfo
      - -Sdjango_celery_beat.schedulers:DatabaseScheduler
    image: ${DVC_VIEWER_BACKEND_IMAGE}:${DVC_VIEWER_RELEASE_VERSION}
    restart: always
    environment:
      <<: *base_settings
