version: "3.4"

services:
  api:
    image: ${DVC_VIEWER_BACKEND_IMAGE}:${DVC_VIEWER_RELEASE_VERSION}
    environment:
      ALLOWED_HOSTS: "*"
      MIGRATE_DB: 1
      DEBUG: "True"
      #GITLAB_CLIENT_ID: 
      #GITLAB_SECRET_KEY: 

      LOGIN_REDIRECT_URL: http://localhost:${UI_PORT:-3000}/dashboard
      LOGIN_ERROR_URL: http://localhost:${UI_PORT:-3000}/
      LOGOUT_REDIRECT_URL: http://localhost:${UI_PORT:-3000}/
      CORS_ORIGIN_WHITELIST: http://localhost:${UI_PORT:-3000}
      SOCIAL_AUTH_REDIRECT_IS_HTTPS: "False"

      <<: &base_settings
        SECRET_KEY: 'sjwx00s&zu5yz&r(fh4i7pi6c4ukf!9a17rdgyfbfwfo#w%9%0'
        DATABASE_URL: psql://postgres:${DB_PASSWORD:-pwd111}@postgres:5432/${DB_NAME:-database}
        #GITHUB_CLIENT_ID: 
        #GITHUB_SECRET_KEY: 
        #GITHUB_WEBHOOK_URL: ${GITHUB_WEBHOOK_URL}
        #GITHUB_WEBHOOK_SECRET: 
        # other services deps
        CELERY_BROKER_URL: redis://redis:${REDIS_PORT:-6379}
        CELERY_RESULT_BACKEND: redis://redis:${REDIS_PORT:-6379}
    ports:
      - ${API_PORT:-8111}:8000
  ui:
    image: ${DVC_VIEWER_UI_IMAGE}:${DVC_VIEWER_RELEASE_VERSION}
    environment:
      API_URL: http://localhost:${API_PORT:-8111}/api
      FLAGS: ${FLAGS:-""}
    ports:
      - ${UI_PORT:-3000}:3000

  worker:
    command: ["celery", "worker", "-Aviewer", "-linfo", "-Pthreads", "-c4"]
    image: ${DVC_VIEWER_BACKEND_IMAGE}:${DVC_VIEWER_RELEASE_VERSION}
    deploy:
      replicas: 2
    environment:
      <<: *base_settings
