version: "3.4"

services:
  redis:
    image: redis:5.0.6-alpine
    restart: always
    ports:
      - 6379:6379

  api:
    depends_on:
      - redis

  beat:
    depends_on:
      - redis

  worker:
    depends_on:
      - redis
